// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPWQDVR9ZNgu3EH7Ff-bN1CteD-8ds044',
    appId: '1:305317874931:web:20c92b94d4f99db03a3b86',
    messagingSenderId: '305317874931',
    projectId: 'auth-4f2c0',
    authDomain: 'auth-4f2c0.firebaseapp.com',
    storageBucket: 'auth-4f2c0.appspot.com',
    measurementId: 'G-WDFTKHH9WQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlzZ-KI4z--ize7JzmxoR4yAl7VjTYQfo',
    appId: '1:305317874931:android:61b128fff5a3102f3a3b86',
    messagingSenderId: '305317874931',
    projectId: 'auth-4f2c0',
    storageBucket: 'auth-4f2c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMe_dqoaPj3RR-3VCXlyTKXa4FBOkqwm8',
    appId: '1:305317874931:ios:9d8ef39a857b82a43a3b86',
    messagingSenderId: '305317874931',
    projectId: 'auth-4f2c0',
    storageBucket: 'auth-4f2c0.appspot.com',
    iosClientId: '305317874931-7fej3td3sb9pc9g0nvdpl9p3fncpqrtn.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMe_dqoaPj3RR-3VCXlyTKXa4FBOkqwm8',
    appId: '1:305317874931:ios:0ce335b2003831fc3a3b86',
    messagingSenderId: '305317874931',
    projectId: 'auth-4f2c0',
    storageBucket: 'auth-4f2c0.appspot.com',
    iosClientId: '305317874931-6401e42k8bhanv8rjnu5aeu5rj8e9ekn.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp.RunnerTests',
  );
}
